#include "BCIEventApplication.hpp"


void BCIEvent::BCIEventApplication::Publish(){
    BEGIN_PARAMETER_DEFINITIONS
    END_PARAMETER_DEFINITIONS



    BEGIN_STATE_DEFINITIONS
    END_STATE_DEFINITIONS
}
